### ISSUE TITLE
don´t return nothing on load button clicked

### ISSUE THREAD

**Issue by frere97** [yasirkula/UnitySimpleFileBrowser#28] opened 2020-11-03 17:38 UTC
using the base code i can't pass from "yield return FileBrowser.WaitForLoadDialog( false, true, null, "Load File", "Load" );", not even the debug return a message, i'm using the version in the asset store

**Comment by yasirkula** [comment] 2020-11-03 17:49
Can I see your coroutine? And make sure to call your coroutine with StartCoroutine.

**Comment by frere97** [comment] 2020-11-03 18:07
IEnumerator ShowLoadDialogCoroutine()
	{
		// Show a load file dialog and wait for a response from user
		// Load file/folder: file, Allow multiple selection: true
		// Initial path: default (Documents), Title: "Load File", submit button text: "Load"
		yield return FileBrowser.WaitForLoadDialog( false, true, null, "Load File", "Load" );

		// Dialog is closed
		// Print whether the user has selected some files/folders or cancelled the operation (FileBrowser.Success)
		Debug.Log( FileBrowser.Success );

		if( FileBrowser.Success )
		{
			// Print paths of the selected files (FileBrowser.Result) (null, if FileBrowser.Success is false)
			for( int i = 0; i < FileBrowser.Result.Length; i++ )
				Debug.Log( FileBrowser.Result[i] );

			// Read the bytes of the first file via FileBrowserHelpers
			// Contrary to File.ReadAllBytes, this function works on Android 10+, as well
			byte[] bytes = FileBrowserHelpers.ReadBytesFromFile( FileBrowser.Result[0] );
		}
	}

**Comment by frere97** [comment] 2020-11-03 18:07
it is the one u use in your github example

**Comment by yasirkula** [comment] 2020-11-03 18:35
You are calling it using `StartCoroutine( ShowLoadDialogCoroutine() );` and not just `ShowLoadDialogCoroutine();`, am I right?

**Comment by frere97** [comment] 2020-11-03 18:44
yes 	StartCoroutine( ShowLoadDialogCoroutine() );

**Comment by frere97** [comment] 2020-11-03 18:45
i've putted a debbug before and after the return, and just the one before was called

**Comment by yasirkula** [comment] 2020-11-03 18:50
This is weird. Are there absolutely no error messages in console? Does the file browser show up properly? Does the log still not show up after closing the dialog?

**Comment by frere97** [comment] 2020-11-03 18:54
the only error that appears is referent for Vr because the window closes, but the vr is still trying to hit a canvas (but i´ve tried in onverlay, the erro does not appears, and i still does not get the message), the window display correctly and the log still does not shows up after closing the window

**Comment by yasirkula** [comment] 2020-11-03 19:44
On which Unity version does this occur? Can I see your complete script so that I can just copy&paste it on my Unity editor and test it?

**Comment by frere97** [comment] 2020-11-03 19:51
2019.4.01f1, it used to work, some weeks ago, but when i reimported the project it broked, the script is the one u provide in the homepage with the name of "example code". i will try something idiot that i should had tried a time ago, restart unity XD

**Comment by frere97** [comment] 2020-11-03 19:55
yeah, restarting unity did not worked

**Comment by frere97** [comment] 2020-11-03 20:00
yeah, reloading unity didn't worked

**Comment by yasirkula** [comment] 2020-11-03 21:14
I've copy&pasted the example script to my 2019.4.0f1 project. I can see the logs without any issues:

![ss](https://user-images.githubusercontent.com/10211608/98041254-ae83bf80-1e32-11eb-9aea-4b4d3a53d7b6.png)

I'd recommend you to create a fresh new project, import the plugin there and see what happens. It will work because it works on my Unity project lol. Then, you need to figure out what's going on with your actual project.

**Comment by frere97** [comment] 2020-11-03 22:28
thanks man XD, i will try to figure out what's happening, if i got something i update in here

**Comment by frere97** [comment] 2020-11-04 13:10
i created a project from zero, and this still does not works XD

**Comment by frere97** [comment] 2020-11-04 13:14
probably is the computer of my work that is blocking the app from exploring and oppening the archive

**Comment by yasirkula** [comment] 2020-11-04 13:32
If you press Cancel, a "False" log must be printed to console, no matter what. I don't know why this isn't the case for you but I could clearly see the logs in my empty project, so I'm closing this Issue :/

**Closed by yasirkula** 2020-11-04 13:32 UTC
Labels: bug

**Comment by frere97** [comment] 2020-11-04 13:52
the problem was me beeing dumb XD

i was putting the prefab in scene and the script to handler him together, so, when the object was beeing deactivated, the script stopped. sorry for making u loose your time

**Comment by yasirkula** [comment] 2020-11-04 14:03
Happy to hear that the issue is resolved :)
